/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect, useRef } from 'react';
import { 
  Briefcase, 
  MessageSquare, 
  Send, 
  User, 
  Bot, 
  ChevronRight, 
  Award, 
  Target,
  RefreshCw,
  CheckCircle2,
  Lock,
  Mail,
  ArrowRight,
  LogOut,
  CreditCard,
  Download,
  HardHat,
  Factory,
  Truck,
  Zap,
  Utensils,
  Monitor,
  DollarSign,
  Stethoscope,
  Shield,
  Megaphone,
  Sprout,
  Car,
  Siren,
  Wrench,
  Clock,
  History,
  Search
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { generateContent } from './services/aiService';
import { Tooltip } from './components/Tooltip';
import { Modal } from './components/Modal';

interface Message {
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}

type AppStep = 'auth' | 'pricing' | 'setup' | 'interview' | 'summary' | 'admin';

declare global {
  interface Window {
    gtag: (...args: any[]) => void;
  }
}

export default function App() {
  const [step, setStep] = useState<AppStep>('auth');
  const [authMode, setAuthMode] = useState<'login' | 'signup'>('signup');
  const [selectedPlan, setSelectedPlan] = useState<'free' | 'beginner' | 'pro' | 'elite' | null>(null);
  const [sessionsUsed, setSessionsUsed] = useState(0);
  const [isPrivacyOpen, setIsPrivacyOpen] = useState(false);
  const [isTermsOpen, setIsTermsOpen] = useState(false);
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [summary, setSummary] = useState<string>('');
  const [isGeneratingSummary, setIsGeneratingSummary] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [jobTitle, setJobTitle] = useState('');
  const [industry, setIndustry] = useState('');
  const [lastAlertCount, setLastAlertCount] = useState<number>(0);
  const [isAnnual, setIsAnnual] = useState(false);
  const [history, setHistory] = useState<any[]>([]);
  const [currentSimulationId, setCurrentSimulationId] = useState<number | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [showSkipLoading, setShowSkipLoading] = useState(false);
  const [isAdmin, setIsAdmin] = useState(false);
  const [twoFactorEnabled, setTwoFactorEnabled] = useState(false);
  const [requires2FA, setRequires2FA] = useState(false);
  const [tempUserId, setTempUserId] = useState<number | null>(null);
  const [twoFactorCode, setTwoFactorCode] = useState('');
  const [isSettingUp2FA, setIsSettingUp2FA] = useState(false);
  const [qrCodeUrl, setQrCodeUrl] = useState('');
  const [setupCode, setSetupCode] = useState('');
  const [twoFactorMethod, setTwoFactorMethod] = useState<'totp' | 'email'>('totp');
  const [emailCodeSent, setEmailCodeSent] = useState(false);
  const [isSendingCode, setIsSendingCode] = useState(false);

  const [authError, setAuthError] = useState<string | null>(null);
  const [loginError, setLoginError] = useState<string | null>(null);

  const navigate = (path: string) => {
    console.log(`[NAVIGATE] to: ${path}`);
    if (path === '/admin/dashboard') {
      setStep('admin');
    } else if (path === '/') {
      setStep('auth');
    } else if (path === '/pricing') {
      setStep('pricing');
    }
  };

  const trackEvent = (name: string, params?: any) => {
    if (window.gtag) {
      window.gtag('event', name, params);
    }
    console.log(`[GA4 EVENT]: ${name}`, params);
  };

  const exportTranscript = () => {
    const transcript = `ENVISIONPATHS INTERVIEW TRANSCRIPT
Position: ${jobTitle}
Industry: ${industry}
Date: ${new Date().toLocaleDateString()}
--------------------------------------------------

${messages.map(msg => {
  const role = msg.role === 'user' ? 'Candidate' : 'Coach';
  const time = msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
  return `[${time}] ${role}: ${msg.text}`;
}).join('\n\n')}

--------------------------------------------------
Generated by EnvisionPaths Career Intelligence`;

    const blob = new Blob([transcript], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `EnvisionPaths_Interview_${jobTitle.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const suggestedRoles: Record<string, string[]> = {
    'Construction': ['Site Supervisor', 'Electrician', 'Plumber', 'HVAC Technician', 'Heavy Equipment Operator', 'Carpenter', 'Mason', 'Ironworker', 'Surveyor', 'Project Coordinator', 'Drywaller', 'Roofer', 'Pipefitter', 'Crane Operator'],
    'Manufacturing': ['Production Manager', 'Quality Control Inspector', 'CNC Machinist', 'Welder', 'Assembly Line Lead', 'Safety Coordinator', 'Millwright', 'Industrial Electrician', 'Tool and Die Maker', 'Maintenance Mechanic', 'Forklift Operator', 'Machine Operator'],
    'Logistics': ['Warehouse Manager', 'Fleet Supervisor', 'Supply Chain Coordinator', 'Forklift Driver', 'Picker Packer', 'Inventory Specialist', 'Delivery Lead', 'Dispatcher', 'Logistics Analyst', 'Operations Lead', 'Truck Driver (CDL)', 'Warehouse Associate'],
    'Energy': ['Solar Panel Installer', 'Wind Turbine Technician', 'Power Plant Operator', 'Utility Lineworker', 'Field Engineer', 'Safety Officer', 'Drilling Supervisor', 'Pipefitter', 'Geologist', 'Instrumentation Tech', 'Lineman', 'Substation Technician'],
    'Hospitality': ['Executive Chef', 'Line Cook', 'Prep Cook', 'Hotel Manager', 'Front Desk Supervisor', 'Maintenance Lead', 'Janitor', 'Housekeeping Manager', 'Sous Chef', 'Event Coordinator', 'Bartender', 'Server', 'Dishwasher'],
    'Technology': ['Software Engineer', 'Product Manager', 'Data Scientist', 'DevOps Engineer', 'UI/UX Designer', 'IT Support Specialist', 'Cybersecurity Analyst', 'Cloud Architect'],
    'Finance': ['Investment Banker', 'Financial Analyst', 'Accountant', 'Risk Manager', 'Portfolio Manager', 'Loan Officer', 'Tax Specialist', 'Auditor'],
    'Healthcare': ['Registered Nurse', 'Medical Assistant', 'Healthcare Administrator', 'Lab Technician', 'Physical Therapist', 'Pharmacist', 'Dental Hygienist', 'Radiologic Tech'],
    'Defense': ['Aerospace Engineer', 'Systems Analyst', 'Project Manager', 'Security Specialist', 'Logistics Analyst', 'Technical Writer', 'Intelligence Analyst'],
    'Marketing': ['Marketing Manager', 'Content Strategist', 'SEO Specialist', 'Brand Manager', 'Social Media Lead', 'Digital Analyst', 'Copywriter', 'Public Relations'],
    'Agriculture': ['Farm Manager', 'Agricultural Mechanic', 'Greenhouse Supervisor', 'Irrigation Specialist', 'Livestock Manager', 'Crop Consultant', 'Harvester', 'Tractor Operator'],
    'Automotive': ['Service Manager', 'Master Technician', 'Body Shop Lead', 'Parts Coordinator', 'Fleet Mechanic', 'Diagnostic Specialist', 'Tire Technician', 'Diesel Mechanic'],
    'PublicSafety': ['Fire Captain', 'Police Sergeant', 'EMS Supervisor', '911 Dispatcher', 'Security Manager', 'Emergency Coordinator', 'Parole Officer', 'Correctional Officer'],
    'GeneralServices': ['Janitor', 'Security Guard', 'Customer Service', 'Retail Associate', 'Stock Clerk', 'Groundskeeper', 'Maintenance Worker', 'Custodian', 'Pest Control Tech', 'Housekeeper']
  };

  const industryIcons: Record<string, any> = {
    'Construction': HardHat,
    'Manufacturing': Factory,
    'Logistics': Truck,
    'Energy': Zap,
    'Hospitality': Utensils,
    'Technology': Monitor,
    'Finance': DollarSign,
    'Healthcare': Stethoscope,
    'Defense': Shield,
    'Marketing': Megaphone,
    'Agriculture': Sprout,
    'Automotive': Car,
    'PublicSafety': Siren,
    'GeneralServices': Wrench
  };

  const chatEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isTyping]);

  useEffect(() => {
    const checkSession = async () => {
      console.log('[APP] Starting session check...');
      console.log('[APP] Current localStorage session_id:', localStorage.getItem('session_id'));
      console.log('[APP] Current URL:', window.location.href);
      
      // Show skip button after 1.5 seconds
      const skipTimeoutId = setTimeout(() => {
        console.log('[APP] Skip loading button triggered');
        setShowSkipLoading(true);
      }, 1500);

      // Safety timeout: force loading to false after 3 seconds
      const timeoutId = setTimeout(() => {
        console.warn('[APP] Session check timed out, forcing loading to false');
        setIsLoading(false);
      }, 3000);

      const urlParams = new URLSearchParams(window.location.search);
      const sessionId = urlParams.get('session_id');
      const planType = urlParams.get('plan_type');

      if (sessionId) {
        try {
          const verifyRes = await fetch('/api/verify-session', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ 
              session_id: sessionId
            })
          });
          if (verifyRes.ok) {
            const contentType = verifyRes.headers.get('content-type');
            if (contentType && contentType.includes('application/json')) {
              const data = await verifyRes.json();
              setSelectedPlan(data.plan_type);
              trackEvent('plan_unlocked', { plan: data.plan_type });
              // Clean up URL
              window.history.replaceState({}, document.title, window.location.pathname);
            }
          }
        } catch (e) {
          console.error('Verification failed');
        }
      }

      try {
        console.log('[APP] Fetching user profile...');
        const user = await fetchProfile();
        console.log('[APP] Profile fetch result:', user ? 'User found' : 'No user');
        if (user) {
          // Only set step to setup if we're currently on auth
          setStep(prev => prev === 'auth' ? 'setup' : prev);
          fetchHistory();
        } else {
          console.log('[APP] No active session found');
        }
      } catch (e) {
        console.error('[APP] Session check failed', e);
      } finally {
        console.log('[APP] Cleaning up session check...');
        clearTimeout(timeoutId);
        clearTimeout(skipTimeoutId);
        setIsLoading(false);
        console.log('[APP] Session check complete');
      }
    };
    checkSession();
  }, []);

  const getAuthHeaders = (existingHeaders: Record<string, string> = {}) => {
    const sessionId = localStorage.getItem('session_id');
    const headers: Record<string, string> = { ...existingHeaders };
    if (sessionId) headers['x-session-id'] = sessionId;
    return headers;
  };

  const fetchProfile = async () => {
    console.log('[APP] fetchProfile called');
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);
    try {
      const headers = getAuthHeaders();
      console.log('[APP] fetchProfile headers:', headers);
      const res = await fetch('/api/user/profile', { 
        headers,
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      console.log('[APP] fetchProfile response status:', res.status);
      
      if (res.ok) {
        const contentType = res.headers.get('content-type');
        if (contentType && contentType.includes('application/json')) {
          const data = await res.json();
          console.log('[APP] fetchProfile data:', data);
          setSelectedPlan(data.user.plan_type);
          setSessionsUsed(data.user.simulations_this_month);
          setIsAdmin(!!data.user.is_admin);
          setTwoFactorEnabled(!!data.user.two_factor_enabled);
          return data.user;
        } else {
          console.error('[APP] Profile fetch returned non-JSON response');
        }
      } else if (res.status === 401) {
        console.warn('[APP] Profile fetch 401 - Session invalid, clearing localStorage');
        localStorage.removeItem('session_id');
      } else {
        const errorText = await res.text();
        console.error('[APP] Profile fetch failed:', res.status, errorText);
      }
    } catch (e) {
      console.error('[APP] Error fetching profile:', e);
    }
    return null;
  };

  const fetchHistory = async () => {
    try {
      const res = await fetch('/api/simulations/history', { headers: getAuthHeaders() });
      if (res.ok) {
        const data = await res.json();
        setHistory(data.history);
      }
    } catch (e) {
      console.error('Failed to fetch history');
    }
  };

  const handleAuth = async (e: React.FormEvent) => {
    e.preventDefault();
    setAuthError(null);
    const endpoint = authMode === 'signup' ? '/api/auth/signup' : '/api/auth/login';
    
    try {
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password })
      });
      
      const contentType = res.headers.get('content-type');
      if (!contentType || !contentType.includes('application/json')) {
        const text = await res.text();
        console.error('Auth error response:', text.substring(0, 100));
        setAuthError('Server error. Please try again later.');
        return;
      }

      const data = await res.json();
      if (res.ok) {
        if (data.sessionId) {
          localStorage.setItem('session_id', data.sessionId);
        }
        if (data.requires_2fa) {
          setRequires2FA(true);
          setTempUserId(data.user_id);
          return;
        }
        setSelectedPlan(data.user.plan_type);
        setIsAdmin(!!data.user.is_admin);
        setTwoFactorEnabled(!!data.user.two_factor_enabled);
        if (authMode === 'signup') {
          setStep('pricing');
        } else {
          setStep('setup');
          fetchHistory();
        }
      } else {
        setAuthError(data.error || 'Authentication failed');
      }
    } catch (e) {
      setAuthError('Network error. Please try again.');
    }
  };

  const sendEmailCode = async () => {
    if (!tempUserId) return;
    setIsSendingCode(true);
    try {
      const res = await fetch('/api/auth/send-email-code', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ user_id: tempUserId })
      });
      const data = await res.json();
      if (res.ok) {
        setEmailCodeSent(true);
        alert('Verification code sent to your email. Please check your inbox (and server logs).');
      } else {
        alert(data.error || 'Failed to send code');
      }
    } catch (e) {
      alert('Network error');
    } finally {
      setIsSendingCode(false);
    }
  };

  const handle2FALogin = async (e: React.FormEvent) => {
    e.preventDefault();
    const endpoint = twoFactorMethod === 'totp' ? '/api/auth/login-2fa' : '/api/auth/verify-email-code';
    const payload = twoFactorMethod === 'totp' 
      ? { user_id: tempUserId, token: twoFactorCode }
      : { user_id: tempUserId, code: twoFactorCode };

    try {
      const res = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });
      const data = await res.json();
      if (res.ok) {
        if (data.sessionId) {
          localStorage.setItem('session_id', data.sessionId);
        }
        setSelectedPlan(data.user.plan_type);
        setIsAdmin(!!data.user.is_admin);
        setTwoFactorEnabled(!!data.user.two_factor_enabled);
        setRequires2FA(false);
        setTempUserId(null);
        setTwoFactorCode('');
        setTwoFactorMethod('totp');
        setEmailCodeSent(false);
        setStep('setup');
        fetchHistory();
      } else {
        alert(data.error || '2FA verification failed');
      }
    } catch (e) {
      alert('Network error');
    }
  };

  const setup2FA = async () => {
    try {
      const res = await fetch('/api/admin/setup-2fa', { 
        method: 'POST',
        headers: getAuthHeaders()
      });
      const data = await res.json();
      if (res.ok) {
        setQrCodeUrl(data.qrCodeUrl);
        setIsSettingUp2FA(true);
      } else {
        alert(data.error);
      }
    } catch (e) {
      alert('Network error');
    }
  };

  const verify2FASetup = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const res = await fetch('/api/admin/verify-2fa', {
        method: 'POST',
        headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ token: setupCode })
      });
      if (res.ok) {
        setTwoFactorEnabled(true);
        setIsSettingUp2FA(false);
        setQrCodeUrl('');
        setSetupCode('');
        alert('2FA enabled successfully');
      } else {
        const data = await res.json();
        alert(data.error || 'Verification failed');
      }
    } catch (e) {
      alert('Network error');
    }
  };

  const reportGlitch = async () => {
    if (!currentSimulationId) return;
    
    if (!confirm("Did the AI glitch or fail to respond correctly? This will end the session and refund your simulation credit.")) return;

    try {
      const res = await fetch('/api/simulations/report-glitch', {
        method: 'POST',
        headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ simulation_id: currentSimulationId })
      });

      if (res.ok) {
        alert("Glitch reported. Your session has been refunded.");
        setStep('dashboard');
        setCurrentSimulationId(null);
        setMessages([]);
        fetchProfile();
      } else {
        const data = await res.json();
        alert(data.error || "Failed to report glitch.");
      }
    } catch (e) {
      console.error("Error reporting glitch:", e);
      alert("An error occurred while reporting the glitch.");
    }
  };
  const handleLogout = async () => {
    localStorage.removeItem('session_id');
    try {
      await fetch('/api/auth/logout', { 
        method: 'POST',
        headers: getAuthHeaders()
      });
    } catch (e) {
      console.error('[AUTH] Logout API call failed:', e);
    }
    setEmail('');
    setPassword('');
    setStep('auth');
    setAuthMode('login');
    setSelectedPlan(null);
    setHistory([]);
    setIsAdmin(false);
    setSessionsUsed(0);
    setTwoFactorEnabled(false);
    setMessages([]);
    setJobTitle('');
    setIndustry('');
    setCurrentSimulationId(null);
    setSummary('');
    setAuthError(null);
    setLoginError(null);
  };

  const selectPlan = async (plan: 'beginner' | 'pro') => {
    // Get current user profile to get the ID
    setAuthError(null);
    try {
      const profileRes = await fetch('/api/user/profile', { headers: getAuthHeaders() });
      if (!profileRes.ok) throw new Error('Not authenticated');
      
      const contentType = profileRes.headers.get('content-type');
      if (!contentType || !contentType.includes('application/json')) {
        const text = await profileRes.text();
        console.error('Expected JSON but got:', text.substring(0, 100));
        throw new Error('Server returned invalid response format');
      }

      const { user } = await profileRes.json();

      // Stripe Payment Links (Replace with your actual links from Stripe Dashboard)
      const paymentLinks: Record<string, string> = {
        beginner: 'https://buy.stripe.com/28EaEY5Is6bfbmxa139R608',
        pro: 'https://buy.stripe.com/cNi14o2wg9nr76h2yB9R609'
      };

      const link = paymentLinks[plan];
      
      // Pass client_reference_id to identify the user in the webhook/redirect
      const checkoutUrl = new URL(link);
      checkoutUrl.searchParams.set('client_reference_id', user.id.toString());
      if (user.email) {
        checkoutUrl.searchParams.set('prefilled_email', user.email);
      }
      
      trackEvent('upgrade_clicked', { plan });
      
      // Use window.open to avoid iframe blocking issues (Stripe blocks iframe loading)
      const win = window.open(checkoutUrl.toString(), '_blank');
      if (!win) {
        // Fallback if popup is blocked
        window.location.href = checkoutUrl.toString();
      }
    } catch (e) {
      console.error('Upgrade error:', e);
      setAuthError('Please sign in to upgrade. If you are signed in, check your connection.');
      setStep('auth');
    }
  };

  const endInterview = async () => {
    setStep('summary');
    setIsGeneratingSummary(true);
    
    try {
      const conversation = messages.map(m => `${m.role.toUpperCase()}: ${m.text}`).join('\n\n');
      const isFree = !selectedPlan || selectedPlan === 'free';
      const prompt = `As an expert career coach at EnvisionPaths, analyze the following mock interview for a ${jobTitle} role. 
      ${isFree ? 'Provide a brief, standard summary including a score and 2 key points.' : 'Provide a comprehensive, advanced performance analysis including:'}
      ${!isFree ? `
      1. Overall Performance Score (out of 10)
      2. Key Strengths (3 points)
      3. Areas for Improvement (3 points)
      4. A final encouraging "Roadmap to Success" for this candidate.
      ` : ''}
      
      Format the response clearly with headings.
      
      Interview Transcript:
      ${conversation}`;

      const response = await generateContent(prompt);
      const summaryText = response.text;
      setSummary(summaryText);

      // Extract score (simple regex)
      const scoreMatch = summaryText.match(/Score:?\s*(\d+)/i) || summaryText.match(/(\d+)\/10/);
      const score = scoreMatch ? parseInt(scoreMatch[1]) : 7;

      // Save to backend
      await fetch('/api/simulations/complete', {
        method: 'POST',
        headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({
          simulation_id: currentSimulationId,
          job_title: jobTitle,
          industry,
          score,
          feedback: summaryText
        })
      });
      
      setCurrentSimulationId(null);
      trackEvent('simulation_completed', { job_title: jobTitle, score });
      fetchHistory();
    } catch (error) {
      console.error("Error generating summary:", error);
      setSummary("We encountered an error generating your summary. Please try again or review your chat history.");
    } finally {
      setIsGeneratingSummary(false);
    }
  };

  const startInterview = async () => {
    if (!jobTitle || isTyping) return;
    
    setIsTyping(true);
    try {
      const res = await fetch('/api/simulations/start', { 
        method: 'POST',
        headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ job_title: jobTitle, industry })
      });
      
      // Handle non-OK responses
      if (!res.ok) {
        let errorMessage = 'Failed to start interview';
        try {
          const contentType = res.headers.get('content-type');
          if (contentType && contentType.includes('application/json')) {
            const data = await res.json();
            errorMessage = data.error || errorMessage;
          } else {
            const text = await res.text();
            console.error('Non-JSON error response:', text);
            errorMessage = `Server Error (${res.status})`;
          }
        } catch (e) {
          console.error('Error parsing error response:', e);
        }
        
        alert(errorMessage);
        if (res.status === 403) setStep('pricing');
        return;
      }

      const data = await res.json();
      setCurrentSimulationId(data.simulation_id);

      setStep('interview');
      setSessionsUsed(prev => prev + 1);
      trackEvent('simulation_started', { job_title: jobTitle });
      
      const prompt = `You are a professional career coach and expert interviewer at EnvisionPaths. 
      I am applying for the position of ${jobTitle} in the ${industry} industry. 
      Please start the interview by introducing yourself briefly and asking the first interview question. 
      Keep your tone professional, encouraging, and insightful.`;

      const response = await generateContent(prompt);
      setMessages([{
        role: 'model',
        text: response.text,
        timestamp: new Date()
      }]);
    } catch (error) {
      console.error("Error starting interview:", error);
    } finally {
      setIsTyping(false);
    }
  };

  const handleSendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isTyping) return;

    const userMessage: Message = {
      role: 'user',
      text: input,
      timestamp: new Date()
    };

    setMessages(prev => [...prev, userMessage]);
    setInput('');
    setIsTyping(true);

    try {
      const history = messages.map(m => ({
        role: m.role,
        parts: [{ text: m.text }]
      }));

      const isFree = !selectedPlan || selectedPlan === 'free';
      const systemInstruction = `You are an expert career coach. 
      Conduct a realistic interview for a ${jobTitle} role. 
      ${isFree ? 'This is a free trial session, so keep the interview concise (max 5 questions total).' : ''}
      After the user answers a question, briefly acknowledge their answer with a "Coach's Tip" (in italics) 
      and then move on to the next insightful interview question. 
      Focus on behavioral, technical, and situational questions.`;

      const response = await generateContent(input, systemInstruction, history);

      const text = response.text;
      setMessages(prev => [...prev, {
        role: 'model',
        text: text,
        timestamp: new Date()
      }]);
    } catch (error) {
      console.error("Error sending message:", error);
    } finally {
      setIsTyping(false);
    }
  };

  return (
    <div className="min-h-screen bg-black font-sans text-white selection:bg-red-600 selection:text-white">
      {isLoading && (
        <div className="fixed inset-0 bg-black/90 backdrop-blur-xl flex flex-col items-center justify-center z-[100] animate-in fade-in duration-500">
          <div className="relative">
            <div className="w-16 h-16 border-4 border-red-500/10 border-t-red-500 rounded-full animate-spin mb-6" />
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="w-8 h-8 bg-red-500/10 rounded-full animate-pulse" />
            </div>
          </div>
          <p className="text-[10px] font-black uppercase tracking-[0.4em] text-zinc-500 animate-pulse">Initializing Intelligence...</p>
          
          <div className="mt-8 text-[8px] text-zinc-600 font-mono uppercase tracking-widest">
            Session: {localStorage.getItem('session_id') ? 'Active' : 'None'}
          </div>

          <div className="flex flex-col items-center gap-4 mt-12">
            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              onClick={() => setIsLoading(false)}
              className="px-6 py-2 border border-white/10 rounded-full text-[10px] font-bold uppercase tracking-widest text-zinc-500 hover:text-white hover:border-white/20 transition-all"
            >
              Skip Loading
            </motion.button>
            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              onClick={() => {
                localStorage.clear();
                document.cookie.split(";").forEach((c) => {
                  document.cookie = c
                    .replace(/^ +/, "")
                    .replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/");
                });
                window.location.reload();
              }}
              className="text-[9px] font-bold uppercase tracking-widest text-zinc-600 hover:text-red-500 transition-all mt-2"
            >
              Clear All Data & Cookies
            </motion.button>
            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              onClick={async () => {
                try {
                  const res = await fetch('/api/debug/logs');
                  const data = await res.json();
                  console.log('--- SERVER LOGS ---');
                  data.logs.forEach((log: string) => console.log(log));
                  console.log('--- END SERVER LOGS ---');
                  alert('Server logs printed to browser console (F12)');
                } catch (e) {
                  alert('Failed to fetch logs');
                }
              }}
              className="text-[9px] font-bold uppercase tracking-widest text-zinc-600 hover:text-blue-500 transition-all mt-2"
            >
              View Server Logs (Console)
            </motion.button>
            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              onClick={async () => {
                try {
                  const res = await fetch('/api/health');
                  const data = await res.json();
                  alert(`Server Status: ${data.status}\nTime: ${data.timestamp}`);
                } catch (e) {
                  alert('Server Unreachable');
                }
              }}
              className="text-[9px] font-bold uppercase tracking-widest text-zinc-600 hover:text-emerald-500 transition-all mt-2"
            >
              Ping Server
            </motion.button>
            <motion.button
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              onClick={() => {
                localStorage.clear();
                window.location.reload();
              }}
              className="text-[9px] font-bold uppercase tracking-widest text-zinc-600 hover:text-red-500 transition-all"
            >
              Hard Reset App
            </motion.button>
          </div>
        </div>
      )}

      {/* Header */}
      {step !== 'auth' && (
        <header className="sticky top-0 z-10 bg-black/80 backdrop-blur-md border-b border-white/10 px-6 py-4">
          <div className="max-w-5xl mx-auto flex items-center justify-between">
            <div className="flex items-center">
              <span className="text-xl font-black tracking-tighter uppercase italic">
                Envision<span className="text-red-500">Paths</span>
              </span>
            </div>
            
            <div className="flex items-center gap-4">
              {step === 'interview' && (
                <>
                  <Tooltip content="Report AI glitch and refund session">
                    <button 
                      onClick={reportGlitch}
                      aria-label="Report glitch"
                      className="text-[10px] font-black uppercase tracking-widest text-zinc-500 hover:text-white px-3 py-2 rounded-md border border-white/5 hover:border-white/20 transition-all"
                    >
                      Report Glitch
                    </button>
                  </Tooltip>
                  <Tooltip content="End current session and generate report">
                    <button 
                      onClick={endInterview}
                      aria-label="End practice session"
                      className="text-xs font-black uppercase tracking-widest text-white bg-red-600 hover:bg-red-700 px-4 py-2 rounded-md border border-white/20 transition-all shadow-lg shadow-red-900/20"
                    >
                      End Session
                    </button>
                  </Tooltip>
                </>
              )}
              <Tooltip content="Manage your subscription" position="bottom">
                <button 
                  onClick={() => setStep('pricing')}
                  aria-label="Billing and subscription"
                  className="text-white/60 hover:text-red-500 transition-colors flex items-center gap-2"
                >
                  <CreditCard size={20} />
                  <span className="text-[10px] font-black uppercase tracking-widest hidden sm:inline">Billing</span>
                </button>
              </Tooltip>
              {isAdmin && (
                <Tooltip content="Admin Dashboard" position="bottom">
                  <button 
                    onClick={() => setStep('admin')}
                    aria-label="Admin Dashboard"
                    className="text-white/60 hover:text-red-500 transition-colors flex items-center gap-2"
                  >
                    <Shield size={20} />
                    <span className="text-[10px] font-black uppercase tracking-widest hidden sm:inline">Admin</span>
                  </button>
                </Tooltip>
              )}
              <Tooltip content="Sign out of your account" position="bottom">
                <button 
                  onClick={handleLogout}
                  aria-label="Logout"
                  className="text-white/60 hover:text-red-500 transition-colors"
                  title="Logout"
                >
                  <LogOut size={20} />
                </button>
              </Tooltip>
            </div>
          </div>
        </header>
      )}

      <main className="max-w-5xl mx-auto p-6">
        <AnimatePresence mode="wait">
          {step === 'auth' ? (
            <motion.div 
              key="auth"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="min-h-[90vh] flex flex-col items-center justify-center py-12"
            >
              <div className="max-w-4xl w-full grid lg:grid-cols-2 gap-12 items-center">
                <div className="space-y-8 text-center lg:text-left">
                  <div className="inline-block px-4 py-1.5 bg-red-600/10 border border-red-600/20 rounded-full">
                    <p className="text-[10px] font-black text-red-500 uppercase tracking-[0.3em]">Professional Career Intelligence</p>
                  </div>
                  <h1 className="text-6xl sm:text-7xl font-black tracking-tighter uppercase italic leading-[0.9]">
                    Master Your <br />
                    <span className="text-red-500">Interview</span>
                  </h1>
                  <p className="text-zinc-300 text-lg max-w-md mx-auto lg:mx-0 leading-relaxed">
                    Strategic interview preparation for modern professionals. Practice with industry-specific scenarios and get real-time feedback to land your dream job.
                  </p>
                  <div className="flex flex-wrap justify-center lg:justify-start gap-6 pt-4">
                    <div className="flex items-center gap-2">
                      <CheckCircle2 size={16} className="text-red-500" />
                      <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-300">Real-time Analysis</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckCircle2 size={16} className="text-red-500" />
                      <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-300">Industry Specific</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <CheckCircle2 size={16} className="text-red-500" />
                      <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-300">Expert Coaching</span>
                    </div>
                  </div>
                </div>

                <div className="bg-zinc-900/50 border border-white/10 p-10 rounded-3xl backdrop-blur-xl shadow-2xl relative">
                  <div className="absolute -top-12 -right-12 w-64 h-64 bg-red-600/10 rounded-full blur-3xl -z-10" />
                  <div className="absolute -bottom-12 -left-12 w-64 h-64 bg-red-600/5 rounded-full blur-3xl -z-10" />
                  
                  <div className="text-center mb-8">
                    <h2 className="text-3xl font-black tracking-tighter uppercase italic mb-2">
                      {requires2FA ? 'Two-Factor Authentication' : authMode === 'login' ? 'Welcome Back' : 'Join Envision'}
                      <span className="text-[8px] opacity-20 ml-2">v1.2</span>
                    </h2>
                    <p className="text-zinc-400 text-sm">
                      {requires2FA 
                        ? 'Enter the 6-digit code from your authenticator app.'
                        : authMode === 'login' 
                        ? 'Enter your credentials to access the platform.' 
                        : 'Create your account to start your journey.'}
                    </p>
                  </div>

                {authError && (
                  <motion.div 
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mb-6 p-4 bg-red-500/10 border border-red-500/20 rounded-xl text-red-500 text-xs font-bold uppercase tracking-widest text-center"
                  >
                    {authError}
                  </motion.div>
                )}

                {/* Security Note */}
                <div className="mb-6 p-4 bg-blue-500/10 border border-blue-500/20 rounded-xl text-blue-400 text-[10px] font-bold uppercase tracking-widest text-center">
                  Note: If you haven't signed up since the security update, please click "Sign Up" below to create your account.
                </div>

                {/* Admin Bypass - Always visible for testing in this environment */}
                <div className="mb-8">
                  {loginError && (
                    <div className="mb-4 p-3 bg-red-500/10 border border-red-500/20 rounded-lg text-red-500 text-[10px] font-bold uppercase tracking-widest text-center">
                      {loginError}
                    </div>
                  )}
                  <button 
                    onClick={async () => {
                      console.log('[AUTH] Admin bypass clicked');
                      setLoginError(null);
                      setIsLoading(true);
                      try {
                        const response = await fetch('/api/admin-login', {
                          method: 'POST',
                          headers: { 'Content-Type': 'application/json' },
                          body: JSON.stringify({ email: 'harrisonw707@gmail.com' })
                        });
                        const data = await response.json();
                        if (data.success) {
                          console.log('[AUTH] Admin login success, sessionId:', data.sessionId);
                          if (data.sessionId) {
                            localStorage.setItem('session_id', data.sessionId);
                          }
                          if (data.user) {
                            setIsAdmin(!!data.user.is_admin);
                            setSelectedPlan(data.user.plan_type);
                            setTwoFactorEnabled(!!data.user.two_factor_enabled);
                          }
                          // Redirect or show admin dashboard
                          navigate('/admin/dashboard');
                        } else {
                          console.error('[AUTH] Admin login failed:', data.error);
                          setLoginError(data.error || 'Admin login failed. Please check credentials or try again.');
                        }
                      } catch (err) {
                        console.error('[AUTH] Admin login server error:', err);
                        setLoginError('Server error. Please try later.');
                      } finally {
                        setIsLoading(false);
                      }
                    }}
                    className="w-full p-5 bg-emerald-600 hover:bg-emerald-700 text-white font-black uppercase tracking-[0.2em] rounded-xl transition-all shadow-lg shadow-emerald-900/20 flex items-center justify-center gap-2 border border-white/20 group cursor-pointer"
                  >
                    One-Click Admin Access
                    <Zap size={18} className="group-hover:scale-110 transition-transform" />
                  </button>
                  <p className="text-[9px] text-zinc-500 uppercase tracking-widest text-center mt-3 font-bold">
                    Special bypass for primary administrator
                  </p>
                  <button 
                    onClick={() => {
                      localStorage.removeItem('session_id');
                      window.location.reload();
                    }}
                    className="w-full mt-4 text-[8px] text-zinc-700 uppercase tracking-widest hover:text-zinc-500 transition-colors"
                  >
                    Clear Local Session
                  </button>
                </div>

                {requires2FA ? (
                  <div className="space-y-6">
                    <div className="flex gap-2 p-1 bg-zinc-900 rounded-xl border border-white/5">
                      <button 
                        onClick={() => { setTwoFactorMethod('totp'); setTwoFactorCode(''); }}
                        className={`flex-1 py-2 text-[10px] font-black uppercase tracking-widest rounded-lg transition-all ${twoFactorMethod === 'totp' ? 'bg-red-600 text-white' : 'text-zinc-500 hover:text-zinc-300'}`}
                      >
                        App Code
                      </button>
                      <button 
                        onClick={() => { setTwoFactorMethod('email'); setTwoFactorCode(''); }}
                        className={`flex-1 py-2 text-[10px] font-black uppercase tracking-widest rounded-lg transition-all ${twoFactorMethod === 'email' ? 'bg-red-600 text-white' : 'text-zinc-500 hover:text-zinc-300'}`}
                      >
                        Email Code
                      </button>
                    </div>

                    {twoFactorMethod === 'email' && !emailCodeSent ? (
                      <div className="text-center space-y-4 py-4">
                        <p className="text-xs text-zinc-400">We can send a one-time verification code to your registered email address.</p>
                        <button 
                          onClick={sendEmailCode}
                          disabled={isSendingCode}
                          className="w-full bg-white text-black font-black uppercase tracking-widest py-4 rounded-xl hover:bg-zinc-200 transition-colors text-xs disabled:opacity-50"
                        >
                          {isSendingCode ? 'Sending...' : 'Send Email Code'}
                        </button>
                      </div>
                    ) : (
                      <form onSubmit={handle2FALogin} className="space-y-5">
                        <div className="space-y-2">
                          <label htmlFor="2fa-code" className="text-[10px] font-bold uppercase tracking-widest text-zinc-300 ml-1">
                            {twoFactorMethod === 'totp' ? 'Authenticator App Code' : 'Email Verification Code'}
                          </label>
                          <div className="relative">
                            <Shield className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" size={18} />
                            <input 
                              id="2fa-code"
                              type="text" 
                              required
                              placeholder="000000"
                              maxLength={6}
                              value={twoFactorCode}
                              onChange={(e) => setTwoFactorCode(e.target.value)}
                              className="w-full pl-12 pr-4 py-4 bg-black border border-white/10 rounded-xl focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none transition-all text-sm tracking-[0.5em] font-mono text-center"
                            />
                          </div>
                        </div>
                        <button 
                          type="submit"
                          className="w-full bg-red-600 hover:bg-red-700 text-white font-black uppercase tracking-[0.2em] py-5 rounded-xl transition-all shadow-lg shadow-red-900/20 flex items-center justify-center gap-2 border border-white/20 group"
                        >
                          Verify & Login
                          <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                        </button>
                        {twoFactorMethod === 'email' && (
                          <button 
                            type="button"
                            onClick={sendEmailCode}
                            className="w-full text-[10px] text-zinc-500 hover:text-red-500 transition-colors uppercase tracking-widest font-bold"
                          >
                            Resend Code
                          </button>
                        )}
                      </form>
                    )}
                    
                    <button 
                      type="button"
                      onClick={() => {
                        setRequires2FA(false);
                        setTwoFactorMethod('totp');
                        setEmailCodeSent(false);
                      }}
                      className="w-full text-xs text-zinc-500 hover:text-zinc-300 transition-colors uppercase tracking-widest font-bold"
                    >
                      Back to Login
                    </button>
                  </div>
                ) : (
                  <React.Fragment>
                    <form onSubmit={handleAuth} className="space-y-5">
                      <div className="space-y-2">
                        <label htmlFor="email" className="text-[10px] font-bold uppercase tracking-widest text-zinc-300 ml-1">Email Address</label>
                        <Tooltip content={authMode === 'login' ? "Enter your registered email" : "Enter your professional email"} position="right">
                          <div className="relative">
                            <Mail className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" size={18} />
                            <input 
                              id="email"
                              name="email"
                              type="email" 
                              required
                              placeholder="name@company.com"
                              value={email}
                              onChange={(e) => setEmail(e.target.value)}
                              className="w-full pl-12 pr-4 py-4 bg-black border border-white/10 rounded-xl focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none transition-all text-sm"
                            />
                          </div>
                        </Tooltip>
                      </div>

                      <div className="space-y-2">
                        <label htmlFor="password" className="text-[10px] font-bold uppercase tracking-widest text-zinc-300 ml-1">Password</label>
                        <Tooltip content="Minimum 8 characters" position="right">
                          <div className="relative">
                            <Lock className="absolute left-4 top-1/2 -translate-y-1/2 text-zinc-400" size={18} />
                            <input 
                              id="password"
                              name="password"
                              type="password" 
                              required
                              placeholder="Enter your password"
                              value={password}
                              onChange={(e) => setPassword(e.target.value)}
                              className="w-full pl-12 pr-4 py-4 bg-black border border-white/10 rounded-xl focus:border-red-500 focus:ring-1 focus:ring-red-500 outline-none transition-all text-sm"
                            />
                          </div>
                        </Tooltip>
                      </div>

                      <Tooltip content={authMode === 'login' ? "Securely access your dashboard" : "Join the Envision community"}>
                        <button 
                          type="submit"
                          className="w-full bg-red-600 hover:bg-red-700 text-white font-black uppercase tracking-[0.2em] py-5 rounded-xl transition-all shadow-lg shadow-red-900/20 flex items-center justify-center gap-2 border border-white/20 group"
                        >
                          {authMode === 'login' ? 'Sign In' : 'Create Account'}
                          <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />
                        </button>
                      </Tooltip>
                    </form>

                    <div className="mt-8 text-center space-y-4">
                      <button 
                        onClick={() => setAuthMode(authMode === 'login' ? 'signup' : 'login')}
                        className="text-xs text-zinc-300 hover:text-red-500 transition-colors block w-full"
                      >
                        {authMode === 'login' ? "Don't have an account? Sign Up" : "Already have an account? Sign In"}
                      </button>
                      <div className="flex justify-center gap-4">
                        <button 
                          type="button"
                          onClick={() => setIsPrivacyOpen(true)}
                          className="text-[10px] text-zinc-300 hover:text-zinc-100 transition-colors uppercase tracking-widest font-bold"
                        >
                          Privacy Policy
                        </button>
                        <button 
                          type="button"
                          onClick={() => setIsTermsOpen(true)}
                          className="text-[10px] text-zinc-300 hover:text-zinc-100 transition-colors uppercase tracking-widest font-bold"
                        >
                          Terms of Service
                        </button>
                      </div>
                      {authMode === 'signup' && (
                        <div className="flex flex-col items-center gap-1 mt-2">
                          <p className="text-[9px] text-zinc-500 uppercase tracking-widest flex items-center gap-1.5">
                            <CheckCircle2 size={10} className="text-red-500" />
                            No spam email. Ever.
                          </p>
                          <p className="text-[9px] text-zinc-500 uppercase tracking-widest flex items-center gap-1.5">
                            <CheckCircle2 size={10} className="text-red-500" />
                            Cancel subscription anytime.
                          </p>
                        </div>
                      )}
                    </div>

                    <div className="mt-12 pt-8 border-t border-white/5">
                      <p className="text-[10px] text-zinc-500 uppercase tracking-[0.2em] font-black mb-6 text-center">Quick Start Guide</p>
                      <div className="grid grid-cols-3 gap-4">
                        <div className="space-y-2">
                          <div className="w-6 h-6 rounded-full bg-red-600/10 border border-red-600/20 flex items-center justify-center text-[10px] font-black text-red-500 mx-auto">1</div>
                          <p className="text-[9px] text-zinc-400 uppercase tracking-widest text-center leading-tight">Click Sign Up Below</p>
                        </div>
                        <div className="space-y-2">
                          <div className="w-6 h-6 rounded-full bg-red-600/10 border border-red-600/20 flex items-center justify-center text-[10px] font-black text-red-500 mx-auto">2</div>
                          <p className="text-[9px] text-zinc-400 uppercase tracking-widest text-center leading-tight">Create Account</p>
                        </div>
                        <div className="space-y-2">
                          <div className="w-6 h-6 rounded-full bg-red-600/10 border border-red-600/20 flex items-center justify-center text-[10px] font-black text-red-500 mx-auto">3</div>
                          <p className="text-[9px] text-zinc-400 uppercase tracking-widest text-center leading-tight">Access Dashboard</p>
                        </div>
                      </div>
                    </div>
                  </React.Fragment>
                )}
</div>
            </div>

              <Modal 
                isOpen={isPrivacyOpen} 
                onClose={() => setIsPrivacyOpen(false)} 
                title="Privacy Policy"
              >
                <div className="space-y-6 text-zinc-300 text-sm leading-relaxed">
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">1. Data Collection</h3>
                    <p>EnvisionPaths collects minimal personal data required for account practice. This includes your email address and the job titles/industries you provide for practice sessions.</p>
                  </section>
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">2. AI Processing</h3>
                    <p>Your interview responses are processed by advanced AI models to provide feedback. We do not use your personal interview data to train public models. Your session data is used exclusively to generate your performance reports.</p>
                  </section>
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">3. Data Security</h3>
                    <p>We implement industry-standard security measures to protect your information. All communications with our servers are encrypted via SSL/TLS.</p>
                  </section>
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">4. Your Rights</h3>
                    <p>You have the right to access, correct, or delete your data at any time. Contact our expert support team for any data-related inquiries.</p>
                  </section>
                </div>
              </Modal>

              <Modal 
                isOpen={isTermsOpen} 
                onClose={() => setIsTermsOpen(false)} 
                title="Terms of Service"
              >
                <div className="space-y-6 text-zinc-300 text-sm leading-relaxed">
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">1. Acceptance of Terms</h3>
                    <p>By accessing EnvisionPaths, you agree to be bound by these professional terms of service. Our platform is designed for professional development and career advancement practice.</p>
                  </section>
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">2. User Conduct</h3>
                    <p>Users must interact with the AI practice session in a professional manner. Any attempt to exploit or manipulate the AI engine for non-career-related purposes may result in immediate account termination.</p>
                  </section>
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">3. Subscription & Billing</h3>
                    <p>Subscription fees are billed in advance on a monthly basis. Free tier users are limited to 2 practice sessions per month. Premium and Pro features are subject to active subscription status.</p>
                  </section>
                  <section>
                    <h3 className="text-white font-bold uppercase tracking-widest mb-2">4. Limitation of Liability</h3>
                    <p>EnvisionPaths provides practice sessions for professional development. We do not guarantee employment or specific career outcomes. The performance score is an AI-generated estimate based on your session input.</p>
                  </section>
                </div>
              </Modal>
            </motion.div>
          ) : step === 'pricing' ? (
            <motion.div 
              key="pricing"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-6xl mx-auto mt-12"
            >
              <div className="text-center mb-12">
                <h2 className="text-5xl font-black tracking-tighter uppercase italic mb-4">
                  {sessionsUsed >= 2 && (!selectedPlan || selectedPlan === 'free') ? 'Ready for more practice?' : 'Level Up Your Career'}
                </h2>
                <p className="text-zinc-400 max-w-2xl mx-auto">
                  {sessionsUsed >= 2 && (!selectedPlan || selectedPlan === 'free') 
                    ? "You’ve mastered your free simulations for now! Ready for more practice? Upgrade to keep the momentum going." 
                    : 'You’re making progress. Choose the plan that fits your current career goals.'}
                </p>
                <div className="mt-4 inline-block px-4 py-1 bg-zinc-800/50 border border-white/5 rounded-full">
                  <p className="text-[10px] font-bold text-zinc-500 uppercase tracking-[0.2em]">
                    {sessionsUsed >= 2 && (!selectedPlan || selectedPlan === 'free') ? 'Free Limit Reached' : 'Build discipline. Master the interview.'}
                  </p>
                </div>

                <div className="mt-10 flex items-center justify-center gap-4">
                  <span className={`text-[10px] font-black uppercase tracking-widest transition-colors ${!isAnnual ? 'text-white' : 'text-zinc-500'}`}>Monthly</span>
                  <button 
                    onClick={() => setIsAnnual(!isAnnual)}
                    className="w-14 h-7 bg-zinc-800 rounded-full p-1 relative transition-colors hover:bg-zinc-700 border border-white/5"
                  >
                    <motion.div 
                      animate={{ x: isAnnual ? 28 : 0 }}
                      className="w-5 h-5 bg-red-600 rounded-full shadow-lg"
                    />
                  </button>
                  <div className="flex items-center gap-2">
                    <span className={`text-[10px] font-black uppercase tracking-widest transition-colors ${isAnnual ? 'text-white' : 'text-zinc-500'}`}>Annual</span>
                    <span className="bg-emerald-500/10 text-emerald-500 text-[8px] font-black px-2 py-0.5 rounded-full uppercase tracking-widest border border-emerald-500/20">Save 20%</span>
                  </div>
                </div>
              </div>

              <div className="grid lg:grid-cols-4 gap-6">
                {/* Free Tier */}
                <div className="bg-zinc-900/30 border border-white/5 p-8 rounded-3xl backdrop-blur-sm flex flex-col hover:border-zinc-700 transition-all group">
                  <div className="mb-8">
                    <h3 className="text-xl font-black uppercase italic mb-2 text-zinc-400">Free</h3>
                    <div className="flex items-baseline gap-1">
                      <span className="text-3xl font-black">$0</span>
                    </div>
                    <p className="text-[10px] text-zinc-500 uppercase font-bold mt-1">Test the system</p>
                  </div>
                  
                  <ul className="space-y-3 mb-10 flex-1">
                    <li className="flex items-center gap-3 text-zinc-400 text-xs">
                      <CheckCircle2 size={14} className="text-zinc-500" />
                      2 simulations / month
                    </li>
                    <li className="flex items-center gap-3 text-zinc-400 text-xs">
                      <CheckCircle2 size={14} className="text-zinc-500" />
                      Basic AI feedback
                    </li>
                    <li className="flex items-center gap-3 text-zinc-400 text-xs">
                      <CheckCircle2 size={14} className="text-zinc-500" />
                      Standard question bank
                    </li>
                    <li className="flex items-center gap-3 text-zinc-400 text-xs">
                      <CheckCircle2 size={14} className="text-zinc-500" />
                      Limited resources
                    </li>
                  </ul>

                  <button 
                    onClick={() => {
                      setSelectedPlan('free');
                      trackEvent('upgrade_clicked', { plan: 'free' });
                      setStep('setup');
                    }}
                    disabled={sessionsUsed >= 2}
                    className={`w-full py-3 text-xs font-black uppercase tracking-widest rounded-xl border transition-all ${
                      selectedPlan === 'free' || !selectedPlan
                        ? 'bg-zinc-800 text-white border-white/20' 
                        : 'bg-transparent text-zinc-400 border-white/5 hover:border-white/20 hover:text-white'
                    } ${sessionsUsed >= 2 ? 'opacity-50 cursor-not-allowed' : ''}`}
                  >
                    {selectedPlan === 'free' || !selectedPlan ? 'Current Plan' : 'Select Free'}
                  </button>
                </div>

                {/* Beginner Tier */}
                <div className="bg-zinc-900/40 border border-white/10 p-8 rounded-3xl backdrop-blur-sm flex flex-col hover:border-blue-500/50 transition-all group relative">
                  <div className="absolute -top-3 left-6 bg-blue-600 px-3 py-1 rounded-full text-[8px] font-black uppercase tracking-widest text-white">
                    30-Day Unlock
                  </div>
                  <div className="mb-8">
                    <h3 className="text-xl font-black uppercase italic mb-2 text-blue-400">Beginner</h3>
                    <div className="flex items-baseline gap-1">
                      <span className="text-3xl font-black">$5</span>
                    </div>
                    <p className="text-[10px] text-zinc-500 uppercase font-bold mt-1">Short-term burst</p>
                  </div>
                  
                  <ul className="space-y-3 mb-10 flex-1">
                    <li className="flex items-center gap-3 text-zinc-300 text-xs">
                      <CheckCircle2 size={14} className="text-blue-500" />
                      Unlimited for 30 days
                    </li>
                    <li className="flex items-center gap-3 text-zinc-300 text-xs">
                      <CheckCircle2 size={14} className="text-blue-500" />
                      Full AI feedback
                    </li>
                    <li className="flex items-center gap-3 text-zinc-300 text-xs">
                      <CheckCircle2 size={14} className="text-blue-500" />
                      Expanded question bank
                    </li>
                    <li className="flex items-center gap-3 text-zinc-300 text-xs">
                      <CheckCircle2 size={14} className="text-blue-500" />
                      Performance tracking
                    </li>
                  </ul>

                  <button 
                    onClick={() => {
                      trackEvent('upgrade_clicked', { plan: 'beginner' });
                      selectPlan('beginner');
                    }}
                    className={`w-full py-3 text-xs font-black uppercase tracking-widest rounded-xl border transition-all ${
                      selectedPlan === 'beginner' 
                        ? 'bg-blue-600 text-white border-blue-500' 
                        : 'bg-zinc-800 hover:bg-zinc-700 text-white border-white/10'
                    }`}
                  >
                    {selectedPlan === 'beginner' ? 'Active' : 'Get Access'}
                  </button>
                </div>

                {/* Pro Tier */}
                <div className="bg-zinc-900/60 border border-red-600/30 p-8 rounded-3xl backdrop-blur-sm flex flex-col hover:border-red-600/60 transition-all group relative">
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-red-600 px-3 py-0.5 rounded-full text-[8px] font-black uppercase tracking-[0.2em] text-white">
                    Most Popular
                  </div>
                  <div className="mb-8">
                    <h3 className="text-xl font-black uppercase italic mb-2 text-red-500">Pro</h3>
                    <div className="flex items-baseline gap-1">
                      <span className="text-3xl font-black">${isAnnual ? '12' : '15'}</span>
                      <span className="text-zinc-500 text-[10px] uppercase font-bold tracking-widest">/ month</span>
                    </div>
                    {isAnnual && (
                      <p className="text-[8px] text-emerald-500 font-black uppercase tracking-widest mt-1">Billed annually ($144)</p>
                    )}
                    <p className="text-[10px] text-zinc-500 uppercase font-bold mt-1">Power users</p>
                  </div>
                  
                  <ul className="space-y-3 mb-10 flex-1">
                    <li className="flex items-center gap-3 text-zinc-200 text-xs">
                      <CheckCircle2 size={14} className="text-red-600" />
                      Advanced AI critique
                    </li>
                    <li className="flex items-center gap-3 text-zinc-200 text-xs">
                      <CheckCircle2 size={14} className="text-red-600" />
                      Behavioral + Technical
                    </li>
                    <li className="flex items-center gap-3 text-zinc-200 text-xs">
                      <CheckCircle2 size={14} className="text-red-600" />
                      Saved history
                    </li>
                  </ul>

                  <button 
                    onClick={() => {
                      trackEvent('upgrade_clicked', { plan: 'pro' });
                      selectPlan('pro');
                    }}
                    className={`w-full py-3 text-xs font-black uppercase tracking-widest rounded-xl border transition-all ${
                      selectedPlan === 'pro' 
                        ? 'bg-red-600 text-white border-red-500' 
                        : 'bg-red-600 hover:bg-red-700 text-white border-red-500'
                    }`}
                  >
                    {selectedPlan === 'pro' ? 'Active' : 'Go Pro'}
                  </button>
                </div>

                {/* Elite Tier */}
                <div className="bg-zinc-900/20 border border-white/5 p-8 rounded-3xl backdrop-blur-sm flex flex-col opacity-40 grayscale group">
                  <div className="mb-8">
                    <h3 className="text-xl font-black uppercase italic mb-2 text-zinc-500">Elite</h3>
                    <div className="flex items-baseline gap-1">
                      <span className="text-3xl font-black">Coming Soon</span>
                    </div>
                    <p className="text-[10px] text-zinc-600 uppercase font-bold mt-1">Future Tier</p>
                  </div>
                  
                  <ul className="space-y-3 mb-10 flex-1">
                    <li className="flex items-center gap-3 text-zinc-600 text-xs">
                      <Lock size={14} />
                      Live mock sessions
                    </li>
                    <li className="flex items-center gap-3 text-zinc-600 text-xs">
                      <Lock size={14} />
                      Custom role simulation
                    </li>
                  </ul>

                  <button 
                    disabled
                    className="w-full py-3 text-xs font-black uppercase tracking-widest rounded-xl border border-white/5 bg-transparent text-zinc-600 cursor-not-allowed"
                  >
                    Reserved
                  </button>
                </div>
              </div>

              <div className="mt-12 text-center">
                <div className="inline-flex items-center gap-2 text-zinc-400 text-sm italic">
                  <Award size={16} />
                  <span>Ready for more practice? Continue sharpening your skills.</span>
                </div>
              </div>
            </motion.div>
          ) : step === 'setup' ? (
            <motion.div 
              key="setup"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-5xl mx-auto mt-12"
            >
              <div className="text-center mb-12">
                <h2 className="text-5xl font-black tracking-tighter uppercase italic mb-4">Prepare for Success</h2>
                <p className="text-zinc-400 max-w-2xl mx-auto">The interview is your opportunity to shine. Select your industry and target role to begin your practice session.</p>
                {(!selectedPlan || selectedPlan === 'free') && (
                  <div className="mt-6 inline-block bg-zinc-800/50 border border-white/5 px-4 py-2 rounded-full">
                    <p className="text-[10px] font-bold text-zinc-400 uppercase tracking-widest">
                      {sessionsUsed} of 2 free simulations used
                    </p>
                  </div>
                )}
              </div>

              <div className="grid lg:grid-cols-3 gap-8">
                {/* Industry Selection Column */}
                <div className="lg:col-span-1 space-y-4">
                  <label className="text-[10px] font-bold uppercase tracking-widest text-red-500 ml-1">1. Select Industry</label>
                  <div className="grid grid-cols-1 gap-2 max-h-[600px] overflow-y-auto pr-2 scrollbar-hide">
                    {Object.keys(suggestedRoles).map((ind) => {
                      const Icon = industryIcons[ind] || Briefcase;
                      return (
                        <button
                          key={ind}
                          onClick={() => {
                            setIndustry(ind);
                            setJobTitle('');
                          }}
                          className={`flex items-center gap-4 p-4 rounded-2xl border transition-all text-left group ${
                            industry === ind 
                              ? 'bg-red-600 border-red-500 text-white shadow-lg shadow-red-900/20' 
                              : 'bg-zinc-900/50 border-white/5 text-zinc-400 hover:border-white/20 hover:bg-zinc-900'
                          }`}
                        >
                          <div className={`w-10 h-10 rounded-xl flex items-center justify-center transition-colors ${
                            industry === ind ? 'bg-white/20' : 'bg-zinc-800 group-hover:bg-zinc-700'
                          }`}>
                            <Icon size={20} className={industry === ind ? 'text-white' : 'text-zinc-300'} />
                          </div>
                          <div>
                            <p className="text-xs font-black uppercase tracking-widest">
                              {ind.replace(/([A-Z])/g, ' $1').trim()}
                            </p>
                          </div>
                        </button>
                      );
                    })}
                  </div>
                </div>

                {/* Role Selection Column */}
                <div className="lg:col-span-2 space-y-6">
                  <div className="space-y-4">
                    <label className="text-[10px] font-bold uppercase tracking-widest text-red-500 ml-1">2. Choose or Type Role</label>
                    
                    <div className="relative">
                      <Search className="absolute left-6 top-1/2 -translate-y-1/2 text-zinc-500" size={20} />
                      <input 
                        id="jobTitle"
                        name="jobTitle"
                        type="text" 
                        placeholder="Search or enter any job title..."
                        value={jobTitle}
                        onChange={(e) => setJobTitle(e.target.value)}
                        className="w-full pl-16 pr-6 py-6 bg-zinc-900 border border-white/10 rounded-3xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition-all text-xl font-bold placeholder:text-zinc-600"
                      />
                    </div>

                    {industry ? (
                      <motion.div 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="bg-zinc-900/30 border border-white/5 rounded-3xl p-8"
                      >
                        <div className="flex items-center justify-between mb-6">
                          <h3 className="text-xs font-black uppercase tracking-widest text-zinc-500">Suggested {industry} Roles</h3>
                          <span className="text-[10px] font-bold text-zinc-600 uppercase tracking-widest">{suggestedRoles[industry].length} Roles Available</span>
                        </div>
                        <div className="grid grid-cols-2 gap-3">
                          {suggestedRoles[industry].map((role) => (
                            <button
                              key={role}
                              onClick={() => setJobTitle(role)}
                              className={`p-4 rounded-xl text-xs font-bold uppercase tracking-wider transition-all border text-left flex items-center justify-between group ${
                                jobTitle === role 
                                  ? 'bg-red-600 border-red-500 text-white' 
                                  : 'bg-zinc-900 border-white/5 text-zinc-400 hover:border-red-500/50 hover:text-zinc-200'
                              }`}
                            >
                              {role}
                              <ChevronRight size={14} className={`transition-transform ${jobTitle === role ? 'translate-x-0' : '-translate-x-2 opacity-0 group-hover:translate-x-0 group-hover:opacity-100'}`} />
                            </button>
                          ))}
                        </div>
                      </motion.div>
                    ) : (
                      <div className="h-[400px] border-2 border-dashed border-white/5 rounded-3xl flex flex-col items-center justify-center text-zinc-600 p-12 text-center">
                        <Target size={48} className="mb-4 opacity-20" />
                        <p className="text-sm font-bold uppercase tracking-widest">Select an industry to see suggested roles</p>
                      </div>
                    )}
                  </div>

                  {/* Simulation History */}
                  {history.length > 0 && (
                    <div className="bg-zinc-900/20 border border-white/5 rounded-3xl p-8">
                      <div className="flex items-center gap-2 mb-6">
                        <History size={16} className="text-red-500" />
                        <h3 className="text-xs font-black uppercase tracking-widest text-zinc-400">Previous Attempts</h3>
                      </div>
                      <div className="space-y-3">
                        {history.slice(0, 3).map((sim) => (
                          <div key={sim.id} className="flex items-center justify-between p-4 bg-black/40 border border-white/5 rounded-xl">
                            <div>
                              <p className="text-xs font-bold text-white uppercase tracking-wider">{sim.job_title}</p>
                              <div className="flex items-center gap-2 mt-1">
                                <span className="text-[9px] text-zinc-500 uppercase font-black tracking-widest">{sim.industry}</span>
                                <span className="text-[9px] text-zinc-600">•</span>
                                <span className="text-[9px] text-zinc-500 uppercase font-black tracking-widest">{new Date(sim.created_at).toLocaleDateString()}</span>
                              </div>
                            </div>
                            <div className="text-right">
                              <p className="text-lg font-black italic text-red-500">{sim.score}/10</p>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  )}

                  <div className="pt-4">
                    <Tooltip content="Launch the AI career coach simulation">
                      <button 
                        onClick={startInterview}
                        disabled={!jobTitle}
                        className="w-full bg-red-600 hover:bg-red-700 disabled:opacity-30 disabled:cursor-not-allowed text-white font-black uppercase tracking-[0.3em] py-8 rounded-3xl shadow-2xl shadow-red-900/40 transition-all flex items-center justify-center gap-4 border border-white/20 group text-xl"
                      >
                        Start Practice Session
                        <ChevronRight size={28} className="group-hover:translate-x-2 transition-transform" />
                      </button>
                    </Tooltip>
                  </div>
                </div>
              </div>

              <div className="mt-16 grid grid-cols-4 gap-6">
                <div className="p-8 bg-zinc-900/50 border border-white/5 rounded-3xl text-center group hover:border-red-500 transition-colors">
                  <Award className="mx-auto text-red-500 mb-4" size={32} />
                  <p className="text-[10px] font-black uppercase text-zinc-300 tracking-widest group-hover:text-white transition-colors">Expert Tips</p>
                </div>
                <div className="p-8 bg-zinc-900/50 border border-white/5 rounded-3xl text-center group hover:border-red-500 transition-colors">
                  <CheckCircle2 className="mx-auto text-red-500 mb-4" size={32} />
                  <p className="text-[10px] font-black uppercase text-zinc-300 tracking-widest group-hover:text-white transition-colors">Skill Validation</p>
                </div>
                <div className="p-8 bg-zinc-900/50 border border-white/5 rounded-3xl text-center group hover:border-red-500 transition-colors">
                  <Target className="mx-auto text-red-500 mb-4" size={32} />
                  <p className="text-[10px] font-black uppercase text-zinc-300 tracking-widest group-hover:text-white transition-colors">Goal Focused</p>
                </div>
                <div className="p-8 bg-zinc-900/50 border border-white/5 rounded-3xl text-center group hover:border-red-500 transition-colors">
                  <RefreshCw className="mx-auto text-red-500 mb-4" size={32} />
                  <p className="text-[10px] font-black uppercase text-zinc-300 tracking-widest group-hover:text-white transition-colors">Infinite Retries</p>
                </div>
              </div>
            </motion.div>
          ) : step === 'interview' ? (
            <motion.div 
              key="interview"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col h-[calc(100vh-180px)]"
            >
              <div className="flex-1 overflow-y-auto space-y-8 pb-8 px-2 scrollbar-hide">
                {(!selectedPlan || selectedPlan === 'free') && (
                  <div className="flex justify-center mb-4">
                    <div className="bg-red-600/10 border border-red-600/20 px-4 py-1.5 rounded-full flex items-center gap-2">
                      <div className="w-1.5 h-1.5 rounded-full bg-red-600 animate-pulse" />
                      <p className="text-[10px] font-black text-red-500 uppercase tracking-[0.2em]">Trial Session Active</p>
                    </div>
                  </div>
                )}
                {messages.map((msg, i) => (
                  <motion.div 
                    key={i}
                    initial={{ opacity: 0, x: msg.role === 'user' ? 20 : -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                  >
                    <div className={`max-w-[85%] flex gap-4 ${msg.role === 'user' ? 'flex-row-reverse' : 'flex-row'}`}>
                      <div className={`w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0 border ${
                        msg.role === 'user' ? 'bg-red-600 border-white/20' : 'bg-zinc-900 border-white/10'
                      }`}>
                        {msg.role === 'user' ? <User size={20} /> : <Bot size={20} className="text-red-500" />}
                      </div>
                      <div className={`p-6 rounded-2xl shadow-lg ${
                        msg.role === 'user' 
                          ? 'bg-zinc-900 border border-red-600/50 text-white rounded-tr-none' 
                          : 'bg-zinc-900/50 border border-white/10 text-zinc-200 rounded-tl-none'
                      }`}>
                        <p className="text-base leading-relaxed whitespace-pre-wrap font-medium">{msg.text}</p>
                        <p className={`text-[9px] mt-4 font-bold uppercase tracking-widest opacity-40 ${msg.role === 'user' ? 'text-right' : 'text-left'}`}>
                          {msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </p>
                      </div>
                    </div>
                  </motion.div>
                ))}
                {isTyping && (
                  <div className="flex justify-start">
                    <div className="bg-zinc-900 border border-white/10 p-5 rounded-2xl rounded-tl-none shadow-sm flex gap-2 items-center">
                      <div className="w-2 h-2 bg-red-600 rounded-full animate-bounce" />
                      <div className="w-2 h-2 bg-red-600 rounded-full animate-bounce [animation-delay:0.2s]" />
                      <div className="w-2 h-2 bg-red-600 rounded-full animate-bounce [animation-delay:0.4s]" />
                    </div>
                  </div>
                )}
                <div ref={chatEndRef} />
              </div>

              <div className="mt-auto pt-6 border-t border-white/10">
                <form onSubmit={handleSendMessage} className="relative">
                  <label htmlFor="chatInput" className="sr-only">Your response</label>
                  <input 
                    id="chatInput"
                    name="chatInput"
                    type="text"
                    placeholder="Provide your response..."
                    value={input}
                    onChange={(e) => setInput(e.target.value)}
                    className="w-full pl-8 pr-20 py-6 bg-zinc-900 border border-white/10 rounded-2xl shadow-2xl focus:border-red-600 focus:ring-1 focus:ring-red-600 outline-none transition-all text-lg"
                  />
                  <Tooltip content="Send your response to the coach">
                    <button 
                      type="submit"
                      disabled={!input.trim() || isTyping}
                      aria-label="Send message"
                      className="absolute right-3 top-1/2 -translate-y-1/2 w-12 h-12 bg-red-600 text-white rounded-xl flex items-center justify-center hover:bg-red-700 disabled:opacity-30 transition-all shadow-lg shadow-red-900/20 border border-white/20"
                    >
                      <Send size={22} />
                    </button>
                  </Tooltip>
                </form>
                <div className="flex justify-between items-center mt-6 px-2">
                  <div className="flex items-center gap-4">
                    <p className="text-[9px] text-zinc-400 uppercase tracking-[0.3em] font-black">
                      Career Intelligence
                    </p>
                    <button 
                      onClick={exportTranscript}
                      className="flex items-center gap-1.5 text-[9px] font-black uppercase tracking-widest text-zinc-500 hover:text-white transition-colors group"
                    >
                      <Download size={12} className="group-hover:translate-y-0.5 transition-transform" />
                      Export Transcript
                    </button>
                  </div>
                  <div className="flex gap-2">
                    <div className="w-1.5 h-1.5 rounded-full bg-red-600 animate-pulse" />
                    <div className="w-1.5 h-1.5 rounded-full bg-red-600/40" />
                    <div className="w-1.5 h-1.5 rounded-full bg-red-600/40" />
                  </div>
                </div>
              </div>
            </motion.div>
          ) : step === 'admin' ? (
            <motion.div 
              key="admin"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="max-w-4xl mx-auto mt-12"
            >
              <div className="bg-zinc-900/50 border border-white/10 p-10 rounded-3xl backdrop-blur-xl">
                <div className="flex items-center justify-between mb-10">
                  <div>
                    <h2 className="text-4xl font-black tracking-tighter uppercase italic mb-2">Admin Dashboard</h2>
                    <p className="text-zinc-400 text-sm uppercase tracking-widest font-bold">Security & System Management</p>
                  </div>
                  <button 
                    onClick={() => setStep('setup')}
                    className="text-xs font-black uppercase tracking-widest text-zinc-400 hover:text-white transition-colors"
                  >
                    Back to App
                  </button>
                </div>

                <div className="grid md:grid-cols-2 gap-8">
                  <div className="space-y-6">
                    <div className="p-6 bg-black/40 border border-white/5 rounded-2xl">
                      <h3 className="text-lg font-black uppercase italic mb-4 flex items-center gap-2">
                        <Shield className="text-red-500" size={20} />
                        Two-Factor Authentication
                      </h3>
                      
                      {twoFactorEnabled ? (
                        <div className="space-y-4">
                          <div className="flex items-center gap-3 text-emerald-500 bg-emerald-500/10 p-4 rounded-xl border border-emerald-500/20">
                            <CheckCircle2 size={20} />
                            <span className="text-xs font-black uppercase tracking-widest">2FA is currently enabled</span>
                          </div>
                          <p className="text-xs text-zinc-400 leading-relaxed">
                            Your administrative account is secured with TOTP. You will be prompted for a code every time you log in.
                          </p>
                        </div>
                      ) : (
                        <div className="space-y-6">
                          {!isSettingUp2FA ? (
                            <div className="space-y-4">
                              <p className="text-xs text-zinc-400 leading-relaxed">
                                2FA is not yet enabled for your account. Enable it now to secure administrative access.
                              </p>
                              <button 
                                onClick={setup2FA}
                                className="w-full bg-white text-black font-black uppercase tracking-widest py-4 rounded-xl hover:bg-zinc-200 transition-colors text-xs"
                              >
                                Setup 2FA
                              </button>
                            </div>
                          ) : (
                            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                              <div className="flex justify-center p-4 bg-white rounded-xl">
                                <img src={qrCodeUrl} alt="2FA QR Code" className="w-48 h-48" />
                              </div>
                              <div className="space-y-4">
                                <p className="text-[10px] text-zinc-400 uppercase tracking-widest font-bold text-center">
                                  Scan this QR code with your authenticator app (Google Authenticator, Authy, etc.)
                                </p>
                                <form onSubmit={verify2FASetup} className="space-y-4">
                                  <input 
                                    type="text" 
                                    placeholder="Enter 6-digit code"
                                    maxLength={6}
                                    value={setupCode}
                                    onChange={(e) => setSetupCode(e.target.value)}
                                    className="w-full bg-black border border-white/10 rounded-xl px-4 py-4 text-center font-mono tracking-[0.5em] focus:border-red-500 outline-none transition-all"
                                  />
                                  <button 
                                    type="submit"
                                    className="w-full bg-red-600 text-white font-black uppercase tracking-widest py-4 rounded-xl hover:bg-red-700 transition-colors text-xs"
                                  >
                                    Verify & Enable
                                  </button>
                                  <button 
                                    type="button"
                                    onClick={() => setIsSettingUp2FA(false)}
                                    className="w-full text-[10px] text-zinc-500 uppercase tracking-widest font-bold hover:text-zinc-300 transition-colors"
                                  >
                                    Cancel Setup
                                  </button>
                                </form>
                              </div>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="space-y-6">
                    <div className="p-6 bg-black/40 border border-white/5 rounded-2xl">
                      <h3 className="text-lg font-black uppercase italic mb-4 flex items-center gap-2">
                        <History className="text-red-500" size={20} />
                        System Status
                      </h3>
                      <div className="space-y-4">
                        <div className="flex items-center justify-between p-3 bg-zinc-800/30 rounded-lg border border-white/5">
                          <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">Database</span>
                          <span className="text-[10px] font-black uppercase tracking-widest text-emerald-500">Operational</span>
                        </div>
                        <div className="flex items-center justify-between p-3 bg-zinc-800/30 rounded-lg border border-white/5">
                          <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">Stripe API</span>
                          <span className="text-[10px] font-black uppercase tracking-widest text-emerald-500">Connected</span>
                        </div>
                        <div className="flex items-center justify-between p-3 bg-zinc-800/30 rounded-lg border border-white/5">
                          <span className="text-[10px] font-bold uppercase tracking-widest text-zinc-400">AI Engine</span>
                          <span className="text-[10px] font-black uppercase tracking-widest text-emerald-500">Ready</span>
                        </div>
                      </div>
                    </div>

                    <div className="p-6 bg-red-900/10 border border-red-500/20 rounded-2xl">
                      <h3 className="text-lg font-black uppercase italic mb-4 flex items-center gap-2 text-red-500">
                        <Zap size={20} />
                        Danger Zone
                      </h3>
                      <p className="text-[10px] text-zinc-400 uppercase tracking-widest font-bold mb-4">
                        Resetting the database will clear all simulations and sessions. Your admin account will persist.
                      </p>
                      <button 
                        onClick={async () => {
                          if (confirm('Are you absolutely sure? This cannot be undone.')) {
                            const res = await fetch('/api/admin/reset-db', { 
                              method: 'POST',
                              headers: getAuthHeaders()
                            });
                            if (res.ok) {
                              alert('Database reset successfully.');
                              window.location.reload();
                            }
                          }
                        }}
                        className="w-full bg-red-600/20 text-red-500 border border-red-500/40 font-black uppercase tracking-widest py-4 rounded-xl hover:bg-red-600 hover:text-white transition-all text-xs"
                      >
                        Reset Database
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </motion.div>
          ) : (
            <motion.div 
              key="summary"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="max-w-3xl mx-auto mt-8"
            >
              <div className="bg-zinc-900 border border-white/10 rounded-3xl p-12 shadow-2xl relative overflow-hidden">
                <div className="absolute top-0 right-0 w-96 h-96 bg-red-600/5 rounded-full -mr-48 -mt-48 blur-3xl" />
                
                <div className="relative z-10">
                  <div className="flex items-center gap-6 mb-12">
                    <div>
                      <h2 className="text-4xl font-black tracking-tighter uppercase italic">Performance Report</h2>
                      <p className="text-red-500 font-bold uppercase tracking-widest text-xs mt-1">{jobTitle}</p>
                    </div>
                  </div>

                  {isGeneratingSummary ? (
                    <div className="space-y-8 py-20">
                      <div className="flex flex-col items-center justify-center gap-6">
                        <RefreshCw className="text-red-600 animate-spin" size={64} />
                        <p className="text-zinc-400 font-black uppercase tracking-[0.3em] animate-pulse">Analyzing Your Session</p>
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-10">
                      <div className="prose prose-invert max-w-none">
                        <div className="whitespace-pre-wrap text-zinc-300 leading-relaxed text-lg font-medium border-l-2 border-red-600 pl-8">
                          {summary}
                        </div>
                      </div>

                      <div className="pt-12 border-t border-white/10 flex gap-6">
                        <Tooltip content="Start a fresh interview session">
                          <button 
                            onClick={() => {
                              setStep('setup');
                              setMessages([]);
                              setSummary('');
                            }}
                            aria-label="Start new practice session"
                            className="flex-1 bg-red-600 text-white font-black uppercase tracking-[0.3em] py-6 rounded-2xl shadow-xl shadow-red-900/40 hover:bg-red-700 transition-all border border-white/20"
                          >
                            New Practice Session
                          </button>
                        </Tooltip>
                        <Tooltip content="Save your performance report as PDF">
                          <button 
                            onClick={() => window.print()}
                            aria-label="Export report to PDF"
                            className="px-10 py-6 bg-zinc-800 text-white font-black uppercase tracking-[0.2em] rounded-2xl hover:bg-zinc-700 transition-all border border-white/10"
                          >
                            Export
                          </button>
                        </Tooltip>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </main>
    </div>
  );
}
